AspMvcEf/AspMvcEf/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AspMvcEf.Models;
using System.Collections;

namespace AspMvcEf.Controllers
{
    public class TestController : Library.Controllers.BaseController<Models.Test>
    {
    }
}

AspMvcEf/AspMvcEf/Controllers/TestDbController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AspMvcEf.Controllers
{
    public class TestDbController : Library.Controllers.BaseController<Models.Test_Db>
    {
        
    }
}

AspMvcEf/AspMvcEf/Controllers/TestGrafController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AspMvcEf.Controllers
{
    public class TestGrafController : Controller
    {
        // GET: Default
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Graf()
        {
            var con = new AspMvcEf.Models.Entities();
            var model = con.Test_Result;
            var musers = model.GroupBy(u => u.Test_User).Select(x => new { k = x.Key, v = x.Count() }).ToDictionary(x=>x.k);
            
            return View();
        }

    }


}

AspMvcEf/AspMvcEf/Controllers/TestUrlController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AspMvcEf.Controllers
{
    public class TestUrlController : Library.Controllers.BaseController<Models.Test_Url>
    {
        
    }
}

AspMvcEf/AspMvcEf/Views/Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta name="description" content="The description of my page" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/Scripts/jquery")
    @Scripts.Render("~/Scripts/jqueryval")
    <script type="text/javascript">
        function addDynamic()
        {
            var item = $(".dynamic").children().last().clone();
            item.appendTo(".dynamic");
            item.addClass("new");
            item.find("*").attr("name", function (k, v) {
                if (v === undefined) return v;

                console.log(k, v);
                var num = v.match(/\[(\d)\]/)[1];
                return v.replace(/\[(\d)\]/, "["+(++num)+"]");
            });
            item.find("*[name$='.Id']").attr("value", "0");
        }
    </script>
</head>
<body>
    <div>
        <ul class="nav">
            <li>
                @Html.ActionLink("Home", "Index", "Home", null, null)
            </li>
            <li>
                @Html.ActionLink("Testy", "Index", "Test", null, null)
                <ul>
                    <li>
                        @Html.ActionLink("Test Typy", "Index", "TestType", null, null)
                    </li>
                </ul>
            </li>

            <li>
                @Html.ActionLink("Test Skupiny", "Index", "TestGroup", null, null)
            </li>
            <li>
                @Html.ActionLink("Plany", "Index", "TestSchedule", null, null)
                <ul>
                    <li>
                        @Html.ActionLink("Vysledky", "Index", "TestResult", null, null)
                    </li>
                    <li>
                        @Html.ActionLink("Url", "Index", "TestUrl", null, null)
                        <ul>
                            <li>
                                @Html.ActionLink("Pouzivatelia", "Index", "TestUser", null, null)
                            </li>
                        </ul>
                    </li>
                    <li>
                        @Html.ActionLink("Databaza", "Index", "TestDb", null, null)
                    </li>
                </ul>
            </li>
            <li>
                @Html.ActionLink("Grafy", "Index", "TestGraf", null, null)
            </li>
        </ul>
        <div class="clear"></div>
    </div>
    <div>@ViewBag.Result</div>
    <div>
        @RenderBody()
    </div>
</body>
</html>