AspMvcEf/AspMvcEf/Models/Test_Group_Ref.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspMvcEf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Group_Ref
    {
        public int Id { get; set; }
        public int Test_Id { get; set; }
        public int Test_Group_Id { get; set; }
    
        public virtual Test Test { get; set; }
        public virtual Test_Group Test_Group { get; set; }
    }
}

AspMvcEf/AspMvcEf/Models/Test_Schedule.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspMvcEf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Test_Schedule()
        {
            this.Test_Result = new HashSet<Test_Result>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Test_Group_Id { get; set; }
        public Nullable<System.DateTime> Time_Start { get; set; }
        public Nullable<int> Flag_Start { get; set; }
        public Nullable<int> Flag_Stop { get; set; }
        public int Test_Url_Id { get; set; }
        public int Test_Db_Id { get; set; }
    
        public virtual Test_Db Test_Db { get; set; }
        public virtual Test_Group Test_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test_Result> Test_Result { get; set; }
        public virtual Test_Url Test_Url { get; set; }
    }
}

AspMvcEf/AspMvcEf/Controllers/TestGroupRefController.cs
using System.Linq;
using System.Web.Mvc;

namespace AspMvcEf.Controllers
{
    public class TestGroupRefController : Library.Controllers.BaseController<Models.Test_Group_Ref>
    {
    }
}

AspMvcEf/AspMvcEf/Controllers/TestScheduleController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace AspMvcEf.Controllers
{
    public class TestScheduleController : Library.Controllers.BaseController<Models.Test_Schedule>
    {
        
        public virtual ActionResult Run(int id)
        {
            Models.Scheduler s = HttpContext.Application["Scheduler"] as Models.Scheduler;
            var item = model.Find(id);

            if (item != null)
            {
                Mutex mutex = new Mutex(false, "Task_" + item.Id);
                if (mutex.WaitOne(1000, false))
                {
                    Thread t = new Thread(() => s.Task(con, item, mutex, false));
                    t.Start();
                    TempData["Result"] = "Spustam test " + id;
                }
                else
                {
                    TempData["Result"] = "Spusteny test stale bezi " + id;
                }

            }
            
            return RedirectToAction("Index");
        }
        
        
    }
}

AspMvcEf/AspMvcEf/Views/Shared/EditorTemplates/Test_Group_Ref.cshtml
@model AspMvcEf.Models.Test_Group_Ref
@{
    var tt2 = new AspMvcEf.Models.Entities().Test.ToList();
}
<table border="1">
    <tr>
        <td>
            @Html.HiddenFor(m => m.Id)
            @Html.HiddenFor(m => m.Test_Group_Id)
            @Html.ActionLink("del", "Remove", "TestGroupRef", new { id = Model.Id }, null)
        </td>
        <td>
            @Html.LabelFor(m => m.Test_Id)
        </td>
        <td>
            @Html.DropDownListFor(m => m.Test_Id, new SelectList(tt2, "Id", "Name"))
        </td>
    </tr>
</table>

AspMvcEf/AspMvcEf/Views/Shared/EditorTemplates/Test_Schedule.cshtml
@model AspMvcEf.Models.Test_Schedule
@{
    var tt = new AspMvcEf.Models.Entities().Test_Group.ToList();
    var tt2 = new AspMvcEf.Models.Entities().Test.ToList();
}
<table border="1">
    <tr>
        <td>
            @Html.EditorFor(m => m.Id)
        </td>
    </tr>
    <tr>
        <td>
            @Html.EditorFor(m => m.Name)
        </td>
    </tr>
    <tr>
        <td>
            @Html.DropDownListFor(m => m.Test_Group_Id, new SelectList(tt, "Id", "Name"))
        </td>
    </tr>
    <tr>
        <td>
            @Html.DropDownListFor(m => m.Test_Id, new SelectList(tt2, "Id", "Id"))
        </td>
    </tr>
</table>